### ISSUE TITLE
fix: 후보자가 체크되지 않아도 질문 보내기 버튼이 눌리고 alert가 뜨는 버그

### ISSUE THREAD

**Issue by koremp** [NullFull/call22nd#36]
- `localhost`에서 후보자가 check 되지 않는 버그
- `vercel`에서 후보자가 checked 되지 않아도 질문 보내기 버튼이 눌리고 `alert`가 뜨는 버그

**Comment by koremp** [comment]
`console.log`로 확인해본 결과 처음 `candidates`를 `fetch`할 때 `candidate.checked` 값이 `true`로 들어가고 있습니다.

**Comment by koremp** [comment]
vercel에서 `ask()`함수에서 현재 리스트의 후보자들의 `checked`옵션으로 필터링하는 검증이 들어가지 않아 추가했습니다.

**Comment by koremp** [comment]
> `console.log`로 확인해본 결과 처음 `candidates`를 `fetch`할 때 `candidate.checked` 값이 `true`로 들어가고 있습니다.

`false`로 잘 들어가고 있었네요. 제가 착각했습니다.

**Comment by koremp** [comment]
localhost 에서 dispatch action이 두번씩 되고 있는데 이건 #40 이슈에서 다루겠습니다

**Comment by nestiank** [comment]
이렇게 이해하면 될까요?
- `localhost`에서 후보자가 check 되지 않는 버그 -> #40
- `vercel`에서 후보자가 checked 되지 않아도 질문 보내기 버튼이 눌리고 `alert`가 뜨는 버그 -> #39

**Comment by koremp** [comment]
네 맞습니다. #39 는 `fix/send-msg-alert-error` 브랜치에서 작업중입니다.
그리고 PR로 작업이 완료된 브랜치는 삭제하는 것이 좋겠습니다.
