### ISSUE TITLE
fix: localhost에서 action dispatch 하면 2번씩 작동

### ISSUE THREAD

**Issue by koremp** [NullFull/call22nd#40]
`localhost`에서 `actions.ToggleItem`등을 dispatch 했을 때 두번씩 작동하는 오류가 있습니다.
`vercel`에서는 오류가 없으니 우선순위가 낮으나, `localhost`에서 테스트를 할 경우 확인이 안되어 불편합니다.

**Comment by koremp** [comment]
`dispatch TOGGLE_ITEM` 액션은 한번씩 되는데 `checked`가 계속 `false`로 나오네요.

**Comment by koremp** [comment]
`dispatch`된 `actions.TOGGLE_ITEM`은 한 번 불러와지는데 그 안의 함수가 두 번 실행되네요.
<img width="232" alt="image" src="https://github.com/NullFull/call22nd/assets/18482476/37fb0dbe-170c-4031-94b5-6403a145eeef">

**Comment by koremp** [comment]
https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode

Next.js 14의 기본 `reactStrictMode`의 설정이 `true`로 되어있어 dispatch한 함수가 두번씩 불러와지는 것을 확인했습니다. 그런데 왜 다른 reducer의 함수들은 왜 한번만 불러오게 되는 것인지 알 수 없네요...

**Comment by nestiank** [comment]
#43 으로 해결되었습니다.
